### ISSUE TITLE
Consider integrating with NativeScript?

### ISSUE THREAD

**Issue by vmandy** [ng-qt/ng-qt#28]
Hi, thanks for the initiative of starting this project. I too am looking for an approach to build cross-platform native desktop apps with TypeScript/JavaScript and Angular.

I was wondering, have you considered integrating your efforts of building a [NodeGUI](https://github.com/nodegui/nodegui) Angular Renderer with the [NativeScript](https://github.com/NativeScript/NativeScript) project?

This could really be a game changing opportunity to elevate the use of these technologies to build native apps for any device!

Thank you for your initiative creating this project. I will be following closely :-)

**Comment by marcus-sa** [comment]
Qt5 supports mobile app development as well, so integrating with NativeScript wouldn't make any sense.

Thanks for the support towards the project :)
