### ISSUE TITLE
lack `@nodegui/nodegui` in package.json and how to build it?

### ISSUE THREAD

**Issue by tigercosmos** [ng-qt/ng-qt#7]
need `@nodegui/nodegui` to npm intall. I don't know how to build it and run.

**Comment by marcus-sa** [comment]
@tigercosmos there's currently an [issue](https://github.com/nodegui/nodegui/issues/34) with NodeGUI where it can't be built when installing through yarn.
I clone the https://github.com/nodegui/nodegui repository, manually build it and then reference it in `package.json`

**Comment by tigercosmos** [comment]
ok. I also want to know what's your build and run command?

**Comment by marcus-sa** [comment]
This is a work in progress mono repository for the platform..
So what do you mean by build and run command?

**Comment by tigercosmos** [comment]
I am wondering how do you let it build and run, since I don't see the commands in `package.json`

**Comment by marcus-sa** [comment]
It has builders and a platform factory which are being consumed by Angular?

**Comment by marcus-sa** [comment]
Your question is really confusing as to how it's supposed to be "run" when there's no context in what you're asking.
